# Generated by Django 3.2.25 on 2025-08-08 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Form Template',
                'verbose_name_plural': 'Form Templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('order_index', models.IntegerField()),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_templates.template')),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RatingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('order_index', models.IntegerField()),
                ('min_value', models.IntegerField(default=1)),
                ('max_value', models.IntegerField(default=5)),
                ('scale_label', models.CharField(default='Rating', max_length=100)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_templates.template')),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('order_index', models.IntegerField()),
                ('options', models.JSONField(default=list)),
                ('allow_multiple', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_templates.template')),
            ],
            options={
                'ordering': ['order_index'],
                'abstract': False,
            },
        ),
    ]
