# Generated by Django 3.2.25 on 2025-08-14 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(validators=[django.core.validators.MinLengthValidator(5)])),
                ('question_type', models.CharField(choices=[('TEXT', 'Text Input'), ('TEXTAREA', 'Text Area'), ('SELECT', 'Single Choice'), ('RADIO', 'Radio Buttons'), ('CHECKBOX', 'Multiple Choice'), ('RATING', 'Rating Scale'), ('DATE', 'Date'), ('EMAIL', 'Email'), ('PHONE', 'Phone Number')], default='TEXT', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('choices', models.JSONField(blank=True, default=list, help_text='List of choices for select/radio/checkbox questions')),
                ('rating_scale', models.PositiveIntegerField(default=5, help_text='Maximum rating value (e.g., 5 for 1-5 scale)')),
                ('rating_labels', models.JSONField(blank=True, default=dict, help_text="Labels for rating scale (e.g., {'1': 'Poor', '5': 'Excellent'})")),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True, help_text='Additional help text shown below the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Question',
                'verbose_name_plural': 'Template Questions',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='ratingquestion',
            name='template',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='instructions',
            field=models.TextField(blank=True, help_text='Instructions shown to referees before filling the form'),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of this template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.DeleteModel(
            name='MCQQuestion',
        ),
        migrations.DeleteModel(
            name='RatingQuestion',
        ),
        migrations.DeleteModel(
            name='TextQuestion',
        ),
        migrations.AddField(
            model_name='question',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='form_templates.template'),
        ),
    ]
