# Generated by Django 3.2.25 on 2025-08-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_user_id_d73ea9_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='core_notifi_created_5c2415_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'is_dismissed'], name='core_notifi_user_id_99aa6c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
    ]
