# Generated by Django 3.2.25 on 2025-08-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional data like IP address, browser info, etc.')),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.form')),
            ],
            options={
                'verbose_name': 'Form Response',
                'verbose_name_plural': 'Form Responses',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(help_text='ID of the question this answers')),
                ('question_type', models.CharField(help_text='Type of question (text, mcq, rating)', max_length=50)),
                ('answer_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responses.response')),
            ],
            options={
                'ordering': ['question_id'],
                'unique_together': {('response', 'question_id')},
            },
        ),
    ]
