# Generated by Django 3.2.25 on 2025-08-08 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_templates', '0001_initial'),
        ('referees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referees.referee')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_templates.template')),
            ],
            options={
                'verbose_name': 'Form Assignment',
                'verbose_name_plural': 'Form Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
